server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db-notion-integration
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.PostgresSQLDialect
    properties:
      hibernate:
        show_sql: true
    jdbc:
      lob.non-contextual-creation: true
  output:
    ansi:
      enabled: Always